### ISSUE TITLE
PHPUnit\Event\TestSuite\Finished

### ISSUE THREAD

**Issue by localheinz** [theseer/phpunit#24]
* [x] suite
* [x] result?
* [x] rename to `PHPUnit\Event\TestSuite\RunFinished`

Related to #1.

**Comment by localheinz** [comment]
@theseer 

I cannot remember, did we agree to inject both

-  an instance of `PHPUnit\Framework\TestSuite`
-  an instance of `PHPUnit\Framework\TestResult`

?

**Comment by theseer** [comment]
Based on the `?` behind the result, we probably weren't sure. I guess both makes most sense?

Either way, whatever we inject, it should be a read only proxy.
